django/raccoon_shop/raccoon_shop/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from core import views
from api import views as api_views
from django.views.decorators.cache import cache_page

from rest_framework import routers

router = routers.DefaultRouter()
router.register('products', api_views.ProductApiView)
router.register('product', api_views.ProductApiViewCUD)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('products/', views.AllProductView.as_view()),
    path('search/', views.SearchView.as_view()),
    path('product/<str:product_id>/', views.ProductView.as_view()),
    path('feedback/', views.FeedbackView.as_view()),
    path('profile/', views.ProfileView.as_view()),
    path('create_product/', views.CreateProduct.as_view()),
    path('edit_product/<int:product_id>/', views.ProductEditView.as_view()),
    path('login/', LoginView.as_view(template_name='login.html')),
    path('logout/', LogoutView.as_view()),
    path('register/', views.RegistrationView.as_view()),
    path('api-auth/', include('rest_framework.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api/v1/', include(router.urls))
    # path('', views.index)
    # path("api/v1/products/", api_views.ProductList.as_view())
]

django/raccoon_shop/core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, pre_save, post_delete, pre_delete, m2m_changed
from django.dispatch import receiver


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=0)
    name = models.CharField(max_length=255)
    description = models.TextField()
    cover_image = models.ImageField(upload_to='products', null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # PRE SAVE

        if self.pk:
            # UPDATE
            pass
        else:
            # CREATE
            from django.core.cache import cache
            cache.delete('index_page')

        instance = super(Product, self).save(*args, **kwargs)
        # POST SAVE
        return instance


@receiver(pre_save, sender=Product)
def after_product_add(sender, **kwargs):
    kwargs['instance'].name = "HAHAHAHAHAH"


class Review(models.Model):
    rating = models.FloatField()
    name = models.CharField(max_length=255)
    message = models.TextField(null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'Product: {self.product} - Review from: {self.name}'


class Feedback(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    
    def __str__(self):
        return f'{self.name} - {self.email}'

django/raccoon_shop/core/forms.py
import time

from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.core.mail import send_mail

from core.models import Feedback, Product


# class FeedbackForm(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     message = forms.CharField(widget=forms.widgets.Textarea(attrs={'cols': 30, 'rows': 5}))
#
#     def clean_name(self):
#         name = self.cleaned_data['name']
#         if not name.replace(' ', '').isalpha():
#             raise forms.ValidationError("Are you a king? NO NUMBERS!")
#         return name
#
#     def save(self):
#         Feedback.objects.create(
#             name=self.cleaned_data['name'],
#             email=self.cleaned_data['email'],
#             message=self.cleaned_data['message']
#         )
from core.tasks import send_feedback_mail


class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = '__all__'


    def save(self, *args, **kwargs):
        obj = super(FeedbackForm, self).save(*args, **kwargs)
        send_feedback_mail.delay(self.cleaned_data['email'])
        return obj



class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('user', )

    def save(self, commit=True, user=None):
        product = super(ProductForm, self).save(commit=False)
        product.user = user
        product.save()
        self.save_m2m()
        return product


# class LoginForm(forms.Form):
#     username = forms.CharField()
#     password = forms.CharField(widget=forms.widgets.PasswordInput())
#
#     def __init__(self, *args, **kwargs):
#         self.request = kwargs.pop('request')
#         super(LoginForm, self).__init__(*args, **kwargs)
#
#     def clean_password(self):
#         user = authenticate(self.request, username=self.cleaned_data['username'], password=self.cleaned_data['password'])
#         if not user:
#             raise forms.ValidationError("Incorrect username or password")


class RegisterForm(forms.ModelForm):
    password_confirm = forms.CharField(widget=forms.widgets.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password_confirm')
        widgets = {
            'password': forms.widgets.PasswordInput()
        }

    def clean_password_confirm(self):
        if self.cleaned_data['password'] != self.cleaned_data['password_confirm']:
            raise forms.ValidationError('Password do not match')
        return self.cleaned_data['password_confirm']

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.save()
        self.save_m2m()
        return user


class ProductAdminForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'tags': forms.widgets.CheckboxSelectMultiple
        }
        # exclude = ('price', )

django/raccoon_shop/core/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView

from api.serrializers import ProductSerializer
from core.forms import ProductForm, RegisterForm, FeedbackForm
from core.models import Product, Review, Feedback
from django.http import JsonResponse


# def index(request):
#     # request.GET  # - GET DATA from browser
#     # request.POST  # - POST DATA from browser
#     # request.FILES  # - FILES sended from browser
#     # return HttpResponse('Hello world')
#     return render(request, 'index.html')

class BaseIndexView(View):

    def dispatch(self, request, *args, **kwargs):
        return super(BaseIndexView, self).dispatch(request, *args, **kwargs)

    def some_my_method(self):
        # self.request
        pass

    def get(self, request):
        return render(request, 'index.html')

    def post(self, request):
        return render(request, 'index.html')


class IndexView(TemplateView):
    template_name = 'index.html'
    extra_context = {'page_title': 'Home'}

    def dispatch(self, request, *args, **kwargs):
        # if user logged in logic
        return super(IndexView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['products'] = Product.objects.all().select_related('user').prefetch_related('tags')[:300]
        return context

    def post(self, request):
        return render(request, 'index.html')


class AllProductView(ListView):
    template_name = 'all_products.html'
    queryset = Product.objects.all()
    context_object_name = 'products'


class SearchView(ListView):
    template_name = 'search.html'

    def get_queryset(self):
        # | - OR
        # & - AND
        # ~ - NOT
        filters = Q()

        if 'q' in self.request.GET:
            search_text = self.request.GET.get('q', ' ')
            filters.add(Q(name__contains=search_text) | Q(description__contains=search_text), Q.AND)

        if 'min-price' in self.request.GET and self.request.GET['min-price']:
            min_price = self.request.GET['min-price']
            filters.add(Q(price__gt=min_price), Q.AND)

        if 'max-price' in self.request.GET and self.request.GET['max-price']:
            max_price = self.request.GET['max-price']
            filters.add(Q(price__lt=max_price), Q.AND)

        if 'is_user_items' not in self.request.GET:
            filters.add(Q(user__isnull=True), Q.AND)

        return Product.objects.filter(filters).select_related('user').prefetch_related('tags')[:100]


class ProfileView(DetailView):
    template_name = 'profile.html'

    def get_object(self, queryset=None):
        return self.request.user


class CreateProduct(CreateView):
    template_name = 'create_product.html'
    model = Product
    form_class = ProductForm
    success_url = '/profile/'

    def form_valid(self, form):
        form.save(user=self.request.user)
        return redirect(self.success_url)


# class ProductEditView(TemplateView):
#     template_name = 'create_product.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(ProductEditView, self).get_context_data(**kwargs)
#         product = Product.objects.get(id=self.kwargs['product_id'])
#         # context['form'] = ProductForm(initial={
#         #     'name': product.name,
#         #     'price': product.price,
#         #     'quantity': product.quantity
#         # })
#         context['form'] = ProductForm(instance=product)
#         return context
#
#     def post(self, request, product_id):
#         product = Product.objects.get(id=product_id)
#         form = ProductForm(instance=product, data=request.POST, files=request.FILES)
#         if form.is_valid():
#             form.save(user=request.user)
#             return redirect('/profile/')
#
#         context = self.get_context_data()
#         context['form'] = form
#         return self.render_to_response(context=context)


# class ProductEditView(FormView):
#     template_name = 'create_product.html'
#     form_class = ProductForm
#     success_url = '/profile/'
#
#     def form_valid(self, form):
#         form.save(user=self.request.user)
#         return super(ProductEditView, self).form_valid(form)
#
#     def get_form_kwargs(self):
#         product = Product.objects.get(id=self.kwargs['product_id'])
#         form_kwargs = super(ProductEditView, self).get_form_kwargs()
#         form_kwargs['instance'] = product
#         return form_kwargs


class ProductEditView(UpdateView):
    template_name = 'create_product.html'
    form_class = ProductForm
    pk_url_kwarg = 'product_id'
    success_url = '/profile/'
    queryset = Product.objects.all()

    def form_valid(self, form):
        form.save(user=self.request.user)
        return redirect(self.success_url)

# class FeedbackView(TemplateView):
#     template_name = 'feedback.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(FeedbackView, self).get_context_data(**kwargs)
#         context['form'] = FeedbackForm()
#         return context
#
#     def post(self, request):
#         context = self.get_context_data()
#         form = FeedbackForm(data=request.POST)
#
#         if form.is_valid():
#             form.save()
#             return redirect('/feedback/')
#
#         context['form'] = form
#         return self.render_to_response(context)


# class FeedbackView(FormView):
#     template_name = 'feedback.html'
#     form_class = FeedbackForm
#     success_url = '/feedback/'
#
#     def form_valid(self, form):
#         form.save()
#         return super(FeedbackView, self).form_valid(form)


class FeedbackView(CreateView):
    template_name = 'feedback.html'
    model = Feedback
    form_class = FeedbackForm
    success_url = '/feedback/'


class ProductView(DetailView):
    template_name = 'product.html'
    model = Product
    pk_url_kwarg = 'product_id'

    def get_queryset(self):
        return Product.objects.filter(quantity__gt=0)

    # def get_object(self, queryset=None):
    #     return Product.objects.get(name=self.kwargs['product_id'])

    # def get_context_data(self, **kwargs):
    #     # self.kwargs['product_id']
    #     return super(ProductView, self).get_context_data(**kwargs)


# FormView, CreateView, UpdateView, DeleteView,
# class IndexView(TemplateView):
#     template_name = 'index.html'
#
#     def get(self, request, *args, **kwargs):
#
#         products = Product.objects.all()  # SELECT * FROM core_product;
#         products = Product.objects.filter(quantity=0)  # SELECT * FROM core_product WHERE quantity=0;
#         products = Product.objects.filter(quantity=0).order_by('name')  # SELECT * FROM core_product WHERE quantity=0 ORDER BY name;
#         # products = products.filter(quantity=0, price=9.99)  # SELECT * FROM core_product WHERE quantity=0 AND price=9.99
#         # products = products.filter(price=9.99)
#         mivina = Product.objects.get(name='Mivina')
#         all_mivina_review_1 = Review.objects.filter(product=mivina)
#
#         all_mivina_review_2 = Review.objects.filter(product__name='Mivina')
#
#         all_food_review = Review.objects.filter(product__tags__name='food')
#
#         available_products = Product.objects.filter(quantity__gt=0)  # WHERE quantity > 0;
#
#         print(all_mivina_review_1)
#         print(all_mivina_review_2)
#         print(all_food_review)
#         print(available_products)
#         return self.render_to_response(self.get_context_data())


# class LoginView(FormView):
#     template_name = 'login.html'
#     form_class = LoginForm
#     success_url = '/profile/'
#
#     def get_form_kwargs(self):
#         form_kwargs = super(LoginView, self).get_form_kwargs()
#         form_kwargs['request'] = self.request
#         return form_kwargs

class RegistrationView(FormView):
    template_name = 'registration.html'
    form_class = RegisterForm
    success_url = '/profile/'

    def form_valid(self, form):
        form.save()
        authenticate(self.request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        return super(RegistrationView, self).form_valid(form)

django/raccoon_shop/core/templates/all_products.html
<ul>
{% for product in products %}
    <li>{{ product.name }} - {{ product.price }}</li>
{% endfor %}
</ul>

django/raccoon_shop/core/templates/base.html
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/feedback/">Feedback</a>
                </li>
              </ul>
              <form class="d-flex" role="search" method="GET" action="/search/" style="margin-bottom: 0px; margin-right: 10px;">
                <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
              <ul class="nav navbar-nav ml-auto">
                  {% if not user.is_authenticated %}
                  <li>
                      <a class="btn btn-primary" href="/login/">Login</a>
                    <a class="btn btn-success" href="/register/">Register</a>
                  </li>
                  {% else %}
                  <li>
                      <a class="btn btn-danger" href="/logout/">Logout</a>
                  </li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </nav>
        <br>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>

django/raccoon_shop/core/templates/create_product.html
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

django/raccoon_shop/core/templates/feedback.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <h1>Feedback</h1>
    <form method="post"> {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Leave feedback</button>
    </form>
{% endblock content %}

django/raccoon_shop/core/templates/index.html
{% extends 'base.html' %}
{% load core_tags %}
{% load cache %}

{% block content %}
    {% with some_new=12 %}
        {{ some_new }}
    {% endwith %}

    {% cache 500 tags %}
        {% for tag in tags %}
            <a href="#">#{{ tag.name }}</a>
        {% endfor %}
    {% endcache %}

    {% random_products %}

    <div class="row">
        {% for product in products %}
            {% include 'includes/product.html' with something='test message' %}
        {% endfor %}
    </div>
{% endblock content %}

django/raccoon_shop/core/templates/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <form method="post">{% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
        <div class="col-md-4">
        </div>
    </div>
{% endblock content %}

django/raccoon_shop/core/templates/product.html
<h1>{{ product.name }}</h1>
<h2>{{ product.price }}</h2>
<h2>{{ description }}</h2>

django/raccoon_shop/core/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <p><b>Username:</b> {{ object.username }}</p>
            <p><b>Email:</b> {{ object.email }}</p>
            <p><b>First name:</b> {{ object.first_name }}</p>
            <p><b>Last name:</b> {{ object.last_name }}</p>
          </div>
        </div>
    </div>
    <div class="col-md-8">
        <a class="btn btn-success" href="/create_product/">Create product</a>
        <div class="row">
            {% for product in object.product_set.all %}
                <div class="col-md-4">
                    <div class="card" style="width: 18rem; margin-top: 20px;">
            {#          <img src="..." class="card-img-top" alt="...">#}
                      <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <a href="/edit_product/{{ product.id }}/" class="btn btn-primary">Edit</a>
                      </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

django/raccoon_shop/core/templates/registration.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <form method="post">{% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
        <div class="col-md-4">
        </div>
    </div>
{% endblock content %}

django/raccoon_shop/core/templates/search.html
{% extends 'base.html' %}
{% load core_tags %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <form method="GET">
                <label>Price</label>
                <input class="form-control" name="min-price" placeholder="min">
                <input class="form-control" name="max-price" placeholder="max">

                <input type="checkbox" checked name="is_user_items"> <label>Is User Items</label>
                <button class="btn btn-primary" type="submit" style="width: 100%">Filter</button>
            </form>
        </div>
        <div class="col-md-9">
            {% random_products %}
            <div class="row">
            {% for product in object_list %}
                {% include 'includes/product.html' %}
            {% empty %}
                <h1 style="text-align: center">No items found</h1>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}